# ORB — LEO Satellite CCN
# Convenience re-export of the COLORS palette from config

from config import COLORS

# Unpack for direct import convenience
BACKGROUND      = COLORS["BACKGROUND"]
EARTH           = COLORS["EARTH"]
EARTH_BORDER    = COLORS["EARTH_BORDER"]
SAT_NOMINAL     = COLORS["SAT_NOMINAL"]
SAT_WARNING     = COLORS["SAT_WARNING"]
SAT_MANEUVERING = COLORS["SAT_MANEUVERING"]
SAT_SAFE        = COLORS["SAT_SAFE"]
ISL_ACTIVE      = COLORS["ISL_ACTIVE"]
ISL_CONGESTED   = COLORS["ISL_CONGESTED"]
DANGER_ZONE     = COLORS["DANGER_ZONE"]
ALERT_PACKET    = COLORS["ALERT_PACKET"]
DATA_PACKET     = COLORS["DATA_PACKET"]
GROUND_STATION  = COLORS["GROUND_STATION"]
TEXT_PRIMARY    = COLORS["TEXT_PRIMARY"]
TEXT_SECONDARY  = COLORS["TEXT_SECONDARY"]
PANEL_BG        = COLORS["PANEL_BG"]
PANEL_BORDER    = COLORS["PANEL_BORDER"]
METRIC_GOOD     = COLORS["METRIC_GOOD"]
METRIC_WARN     = COLORS["METRIC_WARN"]
METRIC_DANGER   = COLORS["METRIC_DANGER"]
